In [5]:
# Create a list of 1,000,000 salaries ranging from 50,000 to 150,000

import random

random.randint(50000, 150000)

93885

In [9]:
sal_list = [random.randint(50_000, 150_000) for x in range(1_000_000)]

In [17]:
import statistics

In [18]:
%%timeit

statistics.mean(sal_list)

416 ms ± 44.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [19]:
import numpy as np

In [20]:
%%timeit

np.mean(sal_list)

55.6 ms ± 1.15 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [21]:
# numpy takes a lot less time than other libraries for analysis

In [23]:
my_array = np.array([1,2,3,4])
my_array

array([1, 2, 3, 4])

In [24]:
my_array.mean()

np.float64(2.5)

In [25]:
# Job titles
job_titles = np.array(['Data Analyst', 'Data Scientist', 'Data Engineer', 'Machine Learning Engineer'])

# Base salaries
base_salaries = np.array([60000, 80000, 75000, 90000])

# Bonus rates
bonus_rates = np.array([.05, .1, .08, .12])

In [27]:
total_salaries = base_salaries * (1 + bonus_rates)
total_salaries

array([ 63000.,  88000.,  81000., 100800.])

In [28]:
np.mean(total_salaries)

np.float64(83200.0)

In [33]:
# having a job title with salary and bonus
# we can use NaN instead of "0" or "None"

# Job titles
job_titles = np.array(['Data Analyst', 'Data Scientist', 'Data Engineer', 'Machine Learning Engineer', 'AI Engineer'])

# Base salaries
base_salaries = np.array([60000, 80000, 75000, 90000, np.nan])

# Bonus rates
bonus_rates = np.array([.05, .1, .08, .12, np.nan])

In [32]:
type(np.nan)

float

In [34]:
total_salaries = base_salaries * (1 + bonus_rates)
total_salaries

array([ 63000.,  88000.,  81000., 100800.,     nan])

In [36]:
np.mean(total_salaries)   # mean can't handle nan values

np.float64(nan)

In [37]:
np.nanmean(total_salaries)

np.float64(83200.0)